name: 'Merge Tag'
description: 'Tag commits on master as they are merged'
inputs:
  repo-token:
    description: "a github token for API access"
    required: true
runs:
  using: 'node12'
  main: 'index.js'
