# This is a basic workflow to help you get started with Actions
on:
  pull_request:
    types: [ opened, synchronize, reopened, closed, edited ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  tag:
    runs-on: ubuntu-latest
    name: tag
    steps:
    - uses: mx51/merge-tag-action@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
